[default]
bpp = 4
transparent = "0x5D53"
output_type = "both"
destination = "./examples/output"
name = ""
metatile_width = 1
metatile_height = 1
palette = ""
palette_include = 0
generate_palette = 0
compress = 0
dedupe = 0
cache = 1

[[unit]]
name = "Sprite5"
metatile_width = 4
metatile_height = 2
palette_include = 1
dedupe = 1

[[unit]]
name = "Sprite9"
metatile_width = 1
metatile_height = 1
palette_include = 1
dedupe = 1
compress = 1
cache = 0