[general]
bpp = 4
transparent = "0x5D53"
output_type = "both"
destination = "./examples/output"

[[unit]]
name = "Sprite5"
metatile_width = 4
metatile_height = 2
palette = ""
palette_include = 1
generate_palette = 0
compress = 0
dedupe = 1

[[unit]]
name = "InventoryBackground"
metatile_width = 1
metatile_height = 1
palette = ""
palette_include = 1
generate_palette = 0
compress = 0
dedupe = 1